// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYt3YPGCtRVRn2eEjvKed80UNFqRLWvw',
    appId: '1:951467405762:web:8f11a7685f55ebe7bce65b',
    messagingSenderId: '951467405762',
    projectId: 'mobile-ecommerce-53fef',
    authDomain: 'mobile-ecommerce-53fef.firebaseapp.com',
    storageBucket: 'mobile-ecommerce-53fef.appspot.com',
    measurementId: 'G-V5N69PQSSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CKP8HHPucxTtSenCgnCeGNUqSoSw5v8',
    appId: '1:951467405762:android:a34eef4c511d7989bce65b',
    messagingSenderId: '951467405762',
    projectId: 'mobile-ecommerce-53fef',
    storageBucket: 'mobile-ecommerce-53fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-7nxEdStZcLS9KhyIc-pq8aqnX4JxO3c',
    appId: '1:951467405762:ios:d8cebd9137b73f43bce65b',
    messagingSenderId: '951467405762',
    projectId: 'mobile-ecommerce-53fef',
    storageBucket: 'mobile-ecommerce-53fef.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-7nxEdStZcLS9KhyIc-pq8aqnX4JxO3c',
    appId: '1:951467405762:ios:53d19941f0499c56bce65b',
    messagingSenderId: '951467405762',
    projectId: 'mobile-ecommerce-53fef',
    storageBucket: 'mobile-ecommerce-53fef.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEComm.RunnerTests',
  );
}
